# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='featured',
        ),
    ]
