# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20160108_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='ancronym',
            field=models.CharField(max_length=10),
        ),
    ]
